// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDD6a93rw23pGVSYc9MipHVExobYqIzke0',
    appId: '1:793852669363:web:89668f6104adf08bccafc6',
    messagingSenderId: '793852669363',
    projectId: 'sidrateams-d9972',
    authDomain: 'sidrateams-d9972.firebaseapp.com',
    databaseURL: 'https://sidrateams-d9972-default-rtdb.firebaseio.com',
    storageBucket: 'sidrateams-d9972.appspot.com',
    measurementId: 'G-DZFYRLTM7X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2Tq8ecfn6G0i28R_HkDPDT38f0chQFuE',
    appId: '1:793852669363:android:07b4a38a8e5bc9acccafc6',
    messagingSenderId: '793852669363',
    projectId: 'sidrateams-d9972',
    databaseURL: 'https://sidrateams-d9972-default-rtdb.firebaseio.com',
    storageBucket: 'sidrateams-d9972.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8TlazNLJJp6dTHNVBzEXIZ1WMCyXdfTE',
    appId: '1:793852669363:ios:821233131f9a5ab0ccafc6',
    messagingSenderId: '793852669363',
    projectId: 'sidrateams-d9972',
    databaseURL: 'https://sidrateams-d9972-default-rtdb.firebaseio.com',
    storageBucket: 'sidrateams-d9972.appspot.com',
    iosBundleId: 'com.rgcopex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8TlazNLJJp6dTHNVBzEXIZ1WMCyXdfTE',
    appId: '1:793852669363:ios:821233131f9a5ab0ccafc6',
    messagingSenderId: '793852669363',
    projectId: 'sidrateams-d9972',
    databaseURL: 'https://sidrateams-d9972-default-rtdb.firebaseio.com',
    storageBucket: 'sidrateams-d9972.appspot.com',
    iosBundleId: 'com.rgcopex',
  );
}
